### ISSUE TITLE
Update to latest CALPADS

### ISSUE THREAD

**Issue by nikolajbaer** [opensandiego/mealscount-backend#20]
Need to get the [embedded data file](https://github.com/opensandiego/mealscount-backend/blob/validate/data/calpads_school_level_1718.csv) updated / replaced with the 2018-2019 school year data.

Note that there are customized column names that we need to account for.

**Comment by aaden2099** [comment]
I uploaded the 2018-2019 school year data in two separate CSV files inside a Google Drive folder. One with the data corresponding to customized column names left as blank on the far right and the other one with that data replaced by original CALPADS data. You'll find a link to the folder below:

https://drive.google.com/open?id=1Hw78rteujPXDtZhvzRxRmznMX9xsXikS

**Comment by nikolajbaer** [comment]
Hi @aaden2099, can you go ahead and replace the existing CSV data in the repo with your updated one? You can change the name and delete the old one 

Thanks!

**Comment by aaden2099** [comment]
No problem. I'll take care of it tomorrow since the most recent CSV file doesn't contain some of the fields in the 17-18 CSV file. I understand that some of those are user generated from formulas so I will go through both files tomorrow and make sure they are identical except with updated data for the new school year. That way, anyone would still be able to run the program using the command below from the Example Usage section with 1718 swapped for 1819:

python cep_estimatory.py data/calpads_school_level_1819.csv OneToOne OneGroup Binning

**Comment by nikolajbaer** [comment]
Hi @aaden2099, were you ever able to get this 1819 data into the repo? I am not seeing it, but maybe it is in a different branch?

**Comment by aaden2099** [comment]
No, I didn't add the 1819 data to the repo. I remember there were a few questions I had about some of the columns which were generated from formulas, since CSV files don't save that info. But, since I wasn't able to attend the last few meetings I couldn't ask you. What I'll do is look at the file again to remember the questions I had and send them to you tomorrow so that you can clarify how you generated those columns of data since for some things they weren't obvious. 

Once I know that, I can just apply the same formulas in Excel and add the file to the repo. I'll also most likely be at next week's meeting since my current job is winding down and I'll be starting a new job in Texas in less than two weeks so I'll try to get as much work done as possible and also add a few helpful resources I found so that if someone else ends up taking over the project they'll have what I've found/learned while doing research.

**Comment by nikolajbaer** [comment]
Note: the file downloads are here:
https://www.cde.ca.gov/ds/sd/sd/filescupc.asp

**Comment by nikolajbaer** [comment]
This has been resolved, closing
